config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions"}
  get 'home/index'
  get 'home/construct'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post 'app/create', to: 'app#create'
  get 'form', to: 'app#form'
  get 'pur', to: 'app#pur'
  get 'admin', to: 'app#admin'
  post 'app/new', to: 'app#new'
  post 'app/min', to: 'app#min'
  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
end

app/models/item_list.rb
class ItemList < ApplicationRecord
end

app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
end

app/models/stock_detail.rb
class StockDetail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/controllers/app_controller.rb
class AppController < ActionController::Base
    

    def form
        me = current_user.id
        @c = User.find(me)  
        @i=ItemCategory.all
        render "layouts/form"
    end    

    def create
       @id=params[:id]
       @i=ItemList.where(itemCategory_id:@id)
       render "layouts/create"
    end 

    def new
        me = current_user.id
        @c = User.find(me)
        require 'date'
        @id=params[:id]
        @tq=params[:TotalQuantity]
        @i=ItemList.where(id:@id)
        @iii=@i.find(@id)
        @s=SaleDetail.new(SaleNo:me, CategoryID:@iii["itemCategory_id"], CategoryName:@iii["CategoryName"], ItemId:@id, ItemName:@iii["ItemName"], TotalQuantity:@tq, ItemPrice:@iii["ItemPrice"], TotalCost:@iii["ItemPrice"]*@tq.to_f, DateofSale:DateTime.now, CustomerName:@c.name, OrderID:22)
        @s.save
        render "layouts/new"
     end 

     def pur
        me=current_user.id 
        @i=SaleDetail.where(SaleNo:me)
        render "layouts/pur"
     end   

     def admin
        render "layouts/ad"
     end 

     def min
        @uu=User.all
        @u=@uu.order(name: :asc)
        @count=User.count
        @s=SaleDetail.all
        @st=StockDetail.all
        @stt=@st.order(ItemName: :asc)
        @x=SaleDetail.where(CategoryName:"Books")
        @xx=@x.order(created_at: :desc)
        @y=SaleDetail.where(CategoryName:"Furniture")
        @yy=@y.order(created_at: :desc)
        @z=SaleDetail.where(CategoryName:"Clothes")
        @zz=@z.order(created_at: :desc)
        @b=@x.sum(:TotalCost)
        @f=@y.sum(:TotalCost)
        @c=@z.sum(:TotalCost)
        for i in 1..15 do
            @d=SaleDetail.where(ItemId:i)
            sum=@d.sum(:TotalQuantity)
            @dd=StockDetail.where(ItemId:i)
            t=@dd[0]["TotalStock"]
            @dd.update(RemainingStock:t-sum, SoldStock:sum)
        end    
        n=params[:name]
        p=params[:password]
     if (n=="Coinbase" && p="coinbase")
        render "layouts/viewww"  
     else   
        render "layouts/ad"
     end   
     end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :remember_me])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :remember_me])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :remember_me])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def construct
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    protected

    def after_sign_up_path_for(resource)
        '/form'
    end

end    

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    protected

    def after_sign_in_path_for(resource)
        '/form'
    end

end   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><h3>Metronic</h3></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
                  <%= link_to 'Home', new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
                  <%= link_to 'About us', home_construct_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
                  <%= link_to 'Settings', home_construct_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Edit User', edit_user_registration_path,class:"nav-link" %>
        </li>
        <div class="left-align left">
        <li class="nav-item"> 
                <%= button_to "Log out", destroy_user_session_path, method: :delete, class:"nav-link bg-primary" %>
        </li> 
        </div>




        <!--<li class="nav-item"> 
                <%= link_to "Log out", destroy_user_session_path, :method => :delete, class:"nav-link" %>
        </li> --> <!-- THIS ISNT WORKING , TO BE CHECKED WHY -->

       




        <!--
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      --> <!-- commented this, might use for future purposes -->


      <!--
      <div class="left-align">
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      </div>
      --> 
    </div>
  </div>
</nav>

app/views/home/construct.html.erb
</br></br></br>
<center>

<h1>OOPS</h1>
<h3>This page is under construction, will be up and running soon</h3>
</center>

app/views/home/index.html.erb
<center>
<h1> Home Page </h1>
</center>

app/views/layouts/ad.html.erb
<%= form_with url:app_min_path, method: :post do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br><br>
    <%=f.submit "Enter" %>
<% end %> 
<style>
body{
    background-image: url('/assets/bgimage.png');
    background-size: 1275px,1000px;
    color: #FFFFFF
    
}
</style>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Metronic</title>
  </head>
  <body>
  <%= render 'home/header' %>

     <%= yield %>

     
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>


<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    

  </body>
</html>

app/views/layouts/create.html.erb
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  margin: 0;
}
.bg {
  background-image: url("https://media.wired.com/photos/60d27192a86e5ac15953a056/1:1/w_1458,h_1458,c_limit/Business-Amazon-Shopping-1279794636.jpg");
  height:100%; 
  background-repeat: no-repeat;
  background-size: cover;
  font-size: 20px;
}
</style>
</head>
<body>
<div class="bg">
<center>
<br> <br>
<%= form_with url:app_new_path, method: :post do |f| %>
    <%= f.select :id, @i.map {|c| [c.ItemName, c.id] } %>
    <br> <br>
    <%= f.label :TotalQuantity %>
    <%= f.number_field :TotalQuantity %>
    <%=f.submit "Enter" %>
<% end %> 
</div>
</center>
</body>
</html>

app/views/layouts/form.html.erb
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  margin: 0;
}
.bg {
  background-image: url("https://media.wired.com/photos/60d27192a86e5ac15953a056/1:1/w_1458,h_1458,c_limit/Business-Amazon-Shopping-1279794636.jpg");
  height:100%; 
  background-repeat: no-repeat;
  background-size: cover;
  font-size: 40px;
}
</style>
</head>
<body>
<div class="bg">
<center>Hello, <%= @c.name %><br> <br>
<%= form_with url:app_create_path, method: :post do |f| %>
    <%= f.select :id, @i.map {|c| [c.CategoryName, c.id] } %>
    <%=f.submit "Enter" %>
<% end %> 
<%= button_to "Log out", destroy_user_session_path, method: :delete %>
<%= button_to "My Orders", pur_path, method: :get %>
</center>
</div>
</body>
</html>

app/views/layouts/new.html.erb
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  margin: 0;
}
.bg {
  background-image: url("https://media.wired.com/photos/60d27192a86e5ac15953a056/1:1/w_1458,h_1458,c_limit/Business-Amazon-Shopping-1279794636.jpg");
  height:100%; 
  background-repeat: no-repeat;
  background-size: cover;
  font-size: 40px;
}
</style>
</head>
<body>
<div class="bg">
<center>
Your order of <%= @s.TotalQuantity %> <%= @s.ItemName %> for Rs.<%= @s.TotalCost %> has been placed successfully.
<hr>
<%= button_to "Buy", form_path, method: :get %> 
<%= button_to "My Orders", pur_path, method: :get %>
<%= button_to "Log out", destroy_user_session_path, method: :delete %>
</center>
</div>
</body>
</html>

app/views/layouts/pur.html.erb
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  margin: 0;
}
.bg {
  background-image: url("https://t4.ftcdn.net/jpg/03/20/68/71/360_F_320687108_3UZ13l44Ob5cel208W7DaRnD5BR9DfY7.jpg");
  background-repeat: no-repeat;
  background-size: 100% 100%;
  font-size: 40px;
  text-align:left;
}
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 25%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 5px;
}
</style>
</head>
<body>
<div class="bg">
<b>Purchase Details</b> <br> <br>
  <table
  <tr>
    <th>Category</th>
    <th>Item</th>              
    <th>Quantity</th>                      
    <th>Cost</th>
    <th>Date/Time</th>
  </tr>
 <% @i.each do |m| %>
  <tr>
    <td><%= m.CategoryName %></td>         
    <td><%= m.ItemName %></td> 
    <td><%= m.TotalQuantity %></td>  
    <td><%= m.TotalCost %></td>
    <td><%= m.DateofSale %></td>    
  </tr>
  <% end %>
 </table> 
 <hr>
 <%= button_to "Log out", destroy_user_session_path, method: :delete %>
 <%= button_to "Buy", form_path, method: :get %>
</div>
</body>
</html>